# Tasks to deploy the application. This might include copying files, setting permissions, and restarting services.


---
- name: Copy application files
  copy:
    src: /path/to/build/
    dest: /var/www/html/
    owner: www-data
    group: www-data

- name: Restart web server
  service:
    name: nginx
    state: restarted
