# This file contains the tasks required to set up the environment before deployment, 
# such as installing necessary dependencies.


---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is started
  service:
    name: nginx
    state: started
